openapi: 3.0.3
info:
  title: Carambar & co - API Blagues
  description: API REST versionnée pour gérer des blagues rigolotes.
  version: "1.0.0"
servers:
  - url: http://localhost:3000/api/v1
    description: Serveur local de développement
paths:
  /blagues:
    get:
      summary: Récupère toutes les blagues
      responses:
        '200':
          description: Liste des blagues
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Blague'
    post:
      summary: Ajoute une nouvelle blague
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BlagueInput'
      responses:
        '201':
          description: Blague créée avec succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Blague'
        '400':
          description: Requête invalide (champs manquants)
  /blagues/{id}:
    get:
      summary: Récupère une blague par ID
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: ID de la blague
      responses:
        '200':
          description: Blague trouvée
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Blague'
        '404':
          description: Blague non trouvée
  /blagues/random:
    get:
      summary: Récupère une blague aléatoire
      responses:
        '200':
          description: Blague aléatoire
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Blague'
        '404':
          description: Aucune blague trouvée
components:
  schemas:
    Blague:
      type: object
      properties:
        id:
          type: integer
          example: 1
        question:
          type: string
          example: "Quelle est la femelle du hamster ?"
        reponse:
          type: string
          example: "L’Amsterdam"
    BlagueInput:
      type: object
      required:
        - question
        - reponse
      properties:
        question:
          type: string
          example: "Quelle est la femelle du hamster ?"
        reponse:
          type: string
          example: "L’Amsterdam"
